### ISSUE TITLE
Accordion event.returnValue is deprecated error

### ISSUE THREAD

**Issue by KishanRathod** [intel/appframeworkPlugins#10]
I am tried to use Accordion plugin with & without App Framework UI and I am getting the following error.

event.returnValue is deprecated. Please use the standard event.preventDefault() instead. appframework.js:338

**Comment by imaffett** [comment]
We do not use "returnValue" in appframework.  can you post up your version with that line it's pointing to?

It's also just a warning message in Chrome browser, we do not support desktop browsers.

**Comment by KishanRathod** [comment]
/**
        \* Extends an object with additional arguments
            `
            $.extend({foo:'bar'});
            $.extend(element,{foo:'bar'});
`

```
    * @param {Object} [target] element
    * @param any number of additional arguments
    * @return {Object} [target]
    * @title $.extend(target,{params})
    */
    $.extend = function(target) {
        if (target == nundefined)
            target = this;
        if (arguments.length === 1) {
            for (var key in target)
                this[key] = target[key];
            return this;
        } else {
            slice.call(arguments, 1).forEach(function(source) {
                for (var key in source)
                    target[key] = source[key];
            });
        }
        return target;
    };
```

![image](https://f.cloud.github.com/assets/5198250/1674405/de2b3f68-5cf8-11e3-9249-6fc0ca52a1bb.png)

**Comment by imaffett** [comment]
Ok  - so somewhere in your code you've called $.extend to extend the AF object..it's executing a function there.

It's not App Framework, it's your code that is calling "event.returnValue"

**Comment by KishanRathod** [comment]
Hummm...It started happening after I added Accordion plugin. You can try following link.
http://online.lubrizol.com/mobilesurvey/test/index.html

it is happening when I initialize Accordion using following statement, it is similar to what we have in Accordion plugin sample. 

$(".accordion").accordion({ time: "0.2s" });

**Comment by KishanRathod** [comment]
I debug the code and it is happening from the af.accordion.js when we add click handler on li.

**Comment by KishanRathod** [comment]
I updated the plugin and sent you a pull request. I am still getting the same warning but I got plugin to work.
