### ISSUE TITLE
Accordion not working without reload

### ISSUE THREAD

**Issue by iampbernardo** [intel/appframeworkPlugins#14]
Working in an APP with Backbone, RequireJS and APP Framework I am having an issue in one of my views with the accordion pluggin.

I have a form whose filelds come from database and are inside an accordion.
If I just navigate to my view url, the accordion is full with the data, but the accordion just doesn't toggle.

Then if i reload the page, it works great.

What could be wrong?

**Comment by imaffett** [comment]
Any chance you can get a basic demo up online that I can try to debug?

**Comment by iampbernardo** [comment]
Not possible for me, sorry.

**Comment by iampbernardo** [comment]
It loks like ti happends because I fill the accordion containers dinamically.
But I reaaly dont't understand why it works when you reload the page.

I tested both on Firefox and Chrome.

**Comment by imaffett** [comment]
Without a test case, I can't help.  If you can get a very basic version that reproduces the issue, I'd be happy to look into it.
