### ISSUE TITLE
There is an error when load subpanels.js on IOS 4.3

### ISSUE THREAD

**Issue by ibuffer** [intel/appframeworkPlugins#5]
Hi,

  I found a issue like the title!

  Safari display an error message like 'SyntaxError : Parse error on line 83'
<code>
that.loadNewDiv(el.old, el.trans, true, el.new);
<code>

el.new is the error source. Please check it !

Lynn

**Comment by imaffett** [comment]
we do not support iOS <5

**Comment by ibuffer** [comment]
So how about android and other platforms?

**Comment by imaffett** [comment]
We support iOS >=5

Android 2.2 - current

Windows Phone 8

Blackberry 10

**Comment by ibuffer** [comment]
Oh, thanks!
It's useful.
I will continue to support appframework.
