### ISSUE TITLE
Show edge of surrounding items

### ISSUE THREAD

**Issue by madebysoren** [intel/appframeworkPlugins#9]
Hi,

This plugin works really well, but I would like to modify it so the edges of the surrounding items are visible for the user and thus encourages them to swipe through the items. Do you have any ideas on how to implement this?

**Comment by madebysoren** [comment]
Ok, it was easier than anticipated. What I did was to add the following css to the container:

width: 90%;
margin: 0 auto;
overflow: visible !important;

If you want some space between the items you should make sure they have margins or only take up around 96% of the width. But evertything works great and no need to change the plugin.

**Comment by imaffett** [comment]
@madebysoren  can you create a PR for the plugin fix?

**Comment by madebysoren** [comment]
But this is not really a fix for the plugin. The css is applied to the container on which the carousel is added.

$("#container").carousel(options);

Would give:

#carousel {
    width: 90%;
    margin: 0 auto;
    overflow: visible !important;
}

**Comment by imaffett** [comment]
Now I understand :)  I may update the demo to show this.

I'm going to close this.  Thanks for the response!

**Comment by madebysoren** [comment]
No problem :)
